### ISSUE TITLE
Ruff GitHub workflow does not fail if code does not follow prescribed style

### ISSUE THREAD

**Issue by ahaselsteiner** [virocon-organization/virocon#229]
Our ruff GitHub workflow does not fail if code does not follow the prescribed style, see https://github.com/virocon-organization/virocon/pull/228

workflow:
```
name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
```

It also looks like charboost is outdated and they recommend to use the [officially supported action form Astral](https://github.com/astral-sh/ruff-action)

![Image](https://github.com/user-attachments/assets/6316bd64-ae94-4bca-98e3-9398686e989b)

cc @kawindme
